service: ib-circle

plugins:
  - serverless-secrets-plugin

custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

provider:
  name: aws
  runtime: nodejs4.3

functions:
  # @todo change function name.
  hello:
    handler: handler.hello
    environment:
      CIRCLECI_TOKEN: ${self:custom.secrets.CIRCLECI_TOKEN}
      PARTICLE_ACCESS_TOKEN: ${self:custom.secrets.PARTICLE_ACCESS_TOKEN}
      PARTICLE_DEVICE_ID: ${self:custom.secrets.PARTICLE_DEVICE_ID}

    events:
      - http:
          # @todo change path name.
          path: ping
          method: get
