
version: 2.1
workflows:
  compile_and_flash:
    jobs:
      - compile
      - flash:
          requires:
            - compile

jobs:
  compile:
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run: npm ci
      - run: pwd
      - run: ls /root/project/node_modules/.bin
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export PATH="/root/project/node_modules/.bin:$PATH"' >> $BASH_ENV
      - run: particle login --token $PARTICLE_TOKEN
      - run: particle list
      - run: particle compile photon button --saveTo ib.bin
      - persist_to_workspace:
          root: .
          paths:
            - .
  flash:
    docker:
      - image: node:10.15.3
    steps:
      - attach_workspace:
          at: .    
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export PATH="/root/project/node_modules/.bin:$PATH"' >> $BASH_ENV
      - run: npm ci
      - run: particle login --token $PARTICLE_TOKEN
      - run: particle list
      - run: particle call balance2 allLedsOn blue
      - run: particle call balance2 rainbow 4
      - run: particle flash balance2 ib.bin
      - run: particle call balance2 allLedsOn blue
      - run: particle call balance2 rainbow 4