
version: 2.1
workflows:
  compile_and_flash:
    jobs:
      - compile

jobs:
  compile:
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run: npm ci
      - run: pwd
      # - run:
      #     name: Setup Environment Variables
      #     command: |
      #       echo 'export PATH="$GOPATH/bin:$PATH"' >> $BASH_ENV
      - run: ./node_modules/.bin/particle
